// Integration checks against ONLY the Supabase CLI's local Amountly stack.
// Synthetic accounts/records are retained locally for inspection. Never loads .env.
const assert = require('node:assert/strict')
const { execFileSync } = require('node:child_process')
const { randomUUID, randomBytes, createHmac } = require('node:crypto')
const { createClient } = require('@supabase/supabase-js')
const loadApp = require('./load-app.cjs')
const { createServerClient } = require('@supabase/ssr')
const appOrigin = process.env.AMOUNTLY_TEST_APP_ORIGIN || 'http://localhost:4174'
if (!['http://127.0.0.1:4174','http://localhost:4174'].includes(appOrigin)) throw Error('Refusing non-local app')
async function cookieHeader(actor) {
  const jar = new Map()
  const client = createServerClient(s.API_URL,s.ANON_KEY,{ cookies: { getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:values=>values.forEach(({name,value})=>jar.set(name,value)) } })
  const { data: { session } } = await actor.client.auth.getSession()
  await ok(client.auth.setSession(session),'prepare server cookie session')
  return [...jar].map(([name,value])=>`${name}=${value}`).join('; ')
}
const s = JSON.parse(execFileSync('supabase', ['status','-o','json'], { encoding: 'utf8', stdio: ['ignore','pipe','ignore'] }))
if (s.API_URL !== 'http://127.0.0.1:54321') throw Error('Refusing non-local Supabase')
const options = { auth: { persistSession: false, autoRefreshToken: false } }
const admin = createClient(s.API_URL, s.SERVICE_ROLE_KEY, options)
const clients = []
const ok = async (promise, label) => { const result = await promise; assert.ok(!result.error, `${label}: ${result.error?.code || 'failed'}`); return result.data }
const denied = async (promise, label) => { const result = await promise; assert.ok(result.error, label) }
const services = client => loadApp({ '@/lib/supabase': { getSupabaseClient: () => client } }, { NEXT_PUBLIC_SUPABASE_URL: s.API_URL })
async function account(type) {
  const email = `release-${randomUUID()}@example.invalid`
  const password = randomBytes(24).toString('base64url')
  const { user } = await ok(admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { name: 'Synthetic release test' } }), 'create local auth fixture')
  const client = createClient(s.API_URL, s.ANON_KEY, options); clients.push(client)
  await ok(client.auth.signInWithPassword({ email, password }), 'sign in')
  const profileApi = services(client)('src/services/profile.service.ts')
  await Promise.all([profileApi.ensureOwnProfile(user, type), profileApi.ensureOwnProfile(user, type)])
  await ok(client.rpc('set_own_account_type', { account_type_param: type }), 'choose account type')
  let org
  if (type === 'business') {
    org = await ok(client.from('organizations').insert({ name: 'Synthetic release workspace' }).select().single(), 'create own organization')
    await ok(client.from('users').update({ organization_id: org.id, role: 'OWNER' }).eq('id', user.id), 'join owned organization')
  }
  const profile = await ok(client.from('users').select('*').eq('id', user.id).single(), 'load onboarded profile')
  assert.equal(profile.account_type, type); assert.equal(profile.is_active, true)
  return { client, user, org, email, password }
}
async function main() {
  const owner = await account('business'), outsider = await account('business'), freelancer = await account('freelancer'), personal = await account('personal')
  await denied(personal.client.from('users').update({ organization_id: owner.org.id, role: 'OWNER' }).eq('id',personal.user.id), 'cannot self-join another workspace')
  console.log('PASS: real Auth + RLS onboarding for business, freelancer and personal; foreign organization joining denied')
  const load = services(owner.client)
  const expenseService = load('src/services/expenses.service.ts')
  const file = new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN9kAAAAASUVORK5CYII=', 'base64')], 'synthetic.png', { type: 'image/png' })
  const receiptPath = await expenseService.uploadReceipt(file)
  const signedUrl = await expenseService.getReceiptUrl({ receipt_path: receiptPath })
  assert.equal((await fetch(signedUrl)).status, 200)
  const signedAt = Date.now()
  await assert.rejects(services(outsider.client)('src/services/expenses.service.ts').getReceiptUrl({ receipt_path: receiptPath }))
  await denied(outsider.client.storage.from('receipts').upload(`${owner.user.id}/${randomUUID()}.png`, file), 'cannot upload to foreign receipt prefix')
  await assert.rejects(expenseService.uploadReceipt(new File(['bad'], 'bad.html', { type: 'text/html' })))
  await assert.rejects(expenseService.uploadReceipt(new File([new Uint8Array(10*1024*1024+1)], 'large.png', { type:'image/png' })))
  await assert.rejects(expenseService.getReceiptUrl({receipt_url:'https://example.invalid/storage/v1/object/sign/receipts/fake'}))
  console.log('PASS: receipt upload/open, cross-workspace signing/upload denial, invalid types/sizes/legacy origins rejected')
  const customer = await ok(owner.client.from('clients').insert({ organization_id: owner.org.id, name: 'Synthetic client' }).select().single(), 'create client')
  const rows = Array.from({length:1005},(_,n)=>({id:randomUUID(),organization_id:owner.org.id,client_id:customer.id,invoice_number:`BULK-${n}`,issue_date:'2026-01-01',due_date:'2026-02-01',subtotal:1,total:1,status:'SENT'}))
  await ok(admin.from('invoices').insert(rows), 'seed large dataset locally')
  await ok(admin.from('invoice_payments').insert(rows.map(row=>({id:randomUUID(),invoice_id:row.id,amount:0.5,paid_on:'2026-01-02',method:'other',recorded_by:owner.user.id}))), 'seed partial payments locally')
  const invoices = await load('src/services/invoices.service.ts').getInvoices()
  assert.equal(invoices.length,1005); assert.equal(new Set(invoices.map(row=>row.id)).size,1005)
  assert.equal(invoices.reduce((total,row)=>total+row.balance_due,0),502.5)
  const exports = load('src/services/exports.service.ts')
  const exported = await exports.getExportRows('invoices'), exportedPayments = await exports.getExportRows('invoice_payments')
  assert.equal(exported.length,1005); assert.equal(exportedPayments.length,1005)
  assert.ok(exported.every(row=>!Object.hasOwn(row,'issued_snapshot')))
  await ok(owner.client.from('expenses').insert({user_id:owner.user.id,expense_date:'2026-01-01',amount:1,receipt_path:receiptPath}), 'save receipt reference')
  const exportedExpenses = await exports.getExportRows('expenses')
  assert.equal(exportedExpenses.length,1); assert.ok(exportedExpenses.every(row=>!Object.hasOwn(row,'receipt_path')&&!Object.hasOwn(row,'receipt_url')))
  assert.equal((await services(outsider.client)('src/services/exports.service.ts').getExportRows('invoices')).length,0)
  await assert.rejects(exports.getExportRows('users'))
  console.log('PASS: actual invoice/payment/export services read all 1,005 rows beyond the API cap; balances, export redaction and isolation verified')
  const invoiceService = load('src/services/invoices.service.ts')
  const second = createClient(s.API_URL,s.ANON_KEY,options);clients.push(second)
  await ok(second.auth.signInWithPassword({email:owner.email,password:owner.password}), 'second independent session')
  const otherSession = services(second)('src/services/invoices.service.ts')
  const id = randomUUID(), input = {client_id:customer.id,issue_date:'2026-01-01',due_date:'2026-02-01',tax_rate:0,currency:'USD'}, lines=[{description:'Retry test',quantity:1,rate:100}]
  await invoiceService.saveInvoiceDraft(id,input,lines)
  const firstView = await invoiceService.getInvoice(id), secondView = await otherSession.getInvoice(id)
  await invoiceService.saveInvoiceDraft(id,{...input,notes:'First writer'},lines,firstView.updated_at)
  await assert.rejects(otherSession.saveInvoiceDraft(id,{...input,notes:'Stale writer'},lines,secondView.updated_at), error=>error.code==='PT409')
  await invoiceService.invoiceAction(await invoiceService.getInvoice(id),'issue')
  // Discard a successful result, as if its response was lost, then retry the same request.
  const payment={id:randomUUID(),amount:40,paid_on:'2026-01-15',method:'other',reference:'Synthetic retry'}
  await invoiceService.recordInvoicePayment(id,payment)
  await otherSession.recordInvoicePayment(id,payment)
  assert.equal((await invoiceService.getInvoice(id)).payments.length,1)
  const race = await Promise.allSettled([invoiceService,otherSession].map(api=>api.recordInvoicePayment(id,{...payment,id:randomUUID(),amount:60})))
  assert.equal(race.filter(result=>result.status==='fulfilled').length,1)
  assert.equal((await invoiceService.getInvoice(id)).balance_due,0)
  console.log('PASS: two real sessions reject stale edits; response-loss retry is idempotent; concurrent final payments cannot overpay')
  const ownerCookie = await cookieHeader(owner), outsiderCookie = await cookieHeader(outsider)
  const pdfUrl = `${appOrigin}/api/invoices/${id}/pdf`
  assert.equal((await fetch(pdfUrl)).status,401)
  assert.equal((await fetch(pdfUrl,{headers:{cookie:outsiderCookie}})).status,404)
  assert.equal((await fetch(`${appOrigin}/api/invoices/not-a-uuid/pdf`,{headers:{cookie:ownerCookie}})).status,400)
  const pdfResponse = await fetch(pdfUrl,{headers:{cookie:ownerCookie}})
  assert.equal(pdfResponse.status,200)
  assert.equal(pdfResponse.headers.get('content-type'),'application/pdf')
  assert.match(pdfResponse.headers.get('cache-control'),/no-store/)
  assert.match(pdfResponse.headers.get('content-disposition'),/^attachment;/)
  assert.equal((await pdfResponse.text()).slice(0,5),'%PDF-')
  const { data: { session: ownerSession } } = await owner.client.auth.getSession()
  const aiHeaders = {origin:appOrigin,authorization:`Bearer ${ownerSession.access_token}`,'content-type':'application/json'}
  const aiBody = JSON.stringify({task:'invoice_line',payload:'Synthetic work at 10'})
  assert.equal((await fetch(`${appOrigin}/api/ai`,{method:'POST',headers:aiHeaders,body:aiBody})).status,503)
  assert.equal((await fetch(`${appOrigin}/api/ai`,{method:'POST',headers:{...aiHeaders,origin:'https://example.invalid'},body:aiBody})).status,403)
  console.log('PASS: production-mode same-origin AI request reaches disabled-provider fallback; cross-origin request denied')
  console.log('PASS: authenticated PDF route renders a real PDF; anonymous, foreign-workspace and malformed requests denied; private/no-store headers set')
  await ok(admin.from('users').update({is_active:false}).eq('id',owner.user.id),'disable synthetic user')
  assert.equal((await invoiceService.getInvoices()).length,0)
  assert.equal((await fetch(pdfUrl,{headers:{cookie:ownerCookie}})).status,404)
  await assert.rejects(expenseService.getReceiptUrl({receipt_path:receiptPath}))
  await assert.rejects(invoiceService.saveInvoiceDraft(randomUUID(),input,lines))
  await ok(admin.from('users').update({is_active:true,role:'MEMBER'}).eq('id',owner.user.id),'demote synthetic user')
  assert.equal((await invoiceService.getInvoices()).length,0)
  await assert.rejects(invoiceService.recordInvoicePayment(id,{...payment,id:randomUUID(),amount:1}))
  await ok(admin.from('users').update({role:'OWNER'}).eq('id',owner.user.id),'restore synthetic role')
  const jwtPart = value => Buffer.from(JSON.stringify(value)).toString('base64url')
  const expired = [jwtPart({alg:'HS256',typ:'JWT'}),jwtPart({sub:owner.user.id,role:'authenticated',aud:'authenticated',exp:1})].join('.')
  const token = `${expired}.${createHmac('sha256',s.JWT_SECRET).update(expired).digest('base64url')}`
  const response = await fetch(`${s.API_URL}/rest/v1/invoices?select=id`,{headers:{apikey:s.ANON_KEY,authorization:`Bearer ${token}`}})
  assert.equal(response.status,401)
  console.log('PASS: disabled users, role changes and expired sessions are denied through real API requests')
  // The application requests 60-second URLs; wait only the remaining lifetime.
  await new Promise(resolve=>setTimeout(resolve,Math.max(0, signedAt+65000-Date.now())))
  assert.notEqual((await fetch(signedUrl,{cache:'no-store'})).status,200)
  const fresh = await expenseService.getReceiptUrl({receipt_path:receiptPath})
  assert.equal((await fetch(fresh)).status,200)
  console.log('PASS: actual 60-second receipt link expires; a fresh authorized link opens')
}
main().catch(error=>{console.error('FAIL:',error.name,error.message);process.exitCode=1}).finally(()=>{for(const client of clients)client.auth.stopAutoRefresh()})
