// Integration checks against ONLY the Supabase CLI's local Amountly stack.
// Synthetic accounts/records are retained locally for inspection. Never loads .env.
const assert = require('node:assert/strict')
const { execFileSync } = require('node:child_process')
const { randomUUID, randomBytes, createHmac } = require('node:crypto')
const { createClient } = require('@supabase/supabase-js')
const loadApp = require('./load-app.cjs')
const { createServerClient } = require('@supabase/ssr')
const appOrigin = process.env.AMOUNTLY_TEST_APP_ORIGIN || 'http://localhost:4174'
if (!['http://127.0.0.1:4174','http://localhost:4174'].includes(appOrigin)) throw Error('Refusing non-local app')
async function cookieHeader(actor) {
  const jar = new Map()
  const client = createServerClient(s.API_URL,s.ANON_KEY,{ cookies: { getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:values=>values.forEach(({name,value})=>jar.set(name,value)) } })
  const { data: { session } } = await actor.client.auth.getSession()
  await ok(client.auth.setSession(session),'prepare server cookie session')
  return [...jar].map(([name,value])=>`${name}=${value}`).join('; ')
}
const s = JSON.parse(execFileSync('supabase', ['status','-o','json'], { encoding: 'utf8', stdio: ['ignore','pipe','ignore'] }))
if (s.API_URL !== 'http://127.0.0.1:54321') throw Error('Refusing non-local Supabase')
const options = { auth: { persistSession: false, autoRefreshToken: false } }
const admin = createClient(s.API_URL, s.SERVICE_ROLE_KEY, options)
const clients = []
const ok = async (promise, label) => { const result = await promise; assert.ok(!result.error, `${label}: ${result.error?.code || 'failed'}`); return result.data }
const denied = async (promise, label) => { const result = await promise; assert.ok(result.error, label) }
const services = client => loadApp({ '@/lib/supabase': { getSupabaseClient: () => client } }, { NEXT_PUBLIC_SUPABASE_URL: s.API_URL })
async function account(type) {
  const email = `release-${randomUUID()}@example.invalid`
  const password = randomBytes(24).toString('base64url')
  const { user } = await ok(admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { name: 'Synthetic release test' } }), 'create local auth fixture')
  const client = createClient(s.API_URL, s.ANON_KEY, options); clients.push(client)
  await ok(client.auth.signInWithPassword({ email, password }), 'sign in')
  const profileApi = services(client)('src/services/profile.service.ts')
  await Promise.all([profileApi.ensureOwnProfile(user, type), profileApi.ensureOwnProfile(user, type)])
  await ok(client.rpc('set_own_account_type', { account_type_param: type }), 'choose account type')
  let org
  if (type === 'business') {
    org = await ok(client.from('organizations').insert({ name: 'Synthetic release workspace' }).select().single(), 'create own organization')
    await ok(client.from('users').update({ organization_id: org.id, role: 'OWNER' }).eq('id', user.id), 'join owned organization')
  }
  const profile = await ok(client.from('users').select('*').eq('id', user.id).single(), 'load onboarded profile')
  assert.equal(profile.account_type, type); assert.equal(profile.is_active, true)
  return { client, user, org, email, password }
}
// Drop a successful response after the database commits, without changing the
// server request. Tests the actual service's ambiguous-outcome behavior.
async function responseLossClient(actor) {
  let target = null, targetMethod = 'POST'
  const client = createClient(s.API_URL,s.ANON_KEY,{...options,global:{fetch:async(input,init)=>{
    const response=await fetch(input,init)
    if(target && new URL(typeof input==='string'?input:input.url || String(input)).pathname.endsWith(target) && (init?.method || 'GET')===targetMethod && response.ok) {
      if (targetMethod !== 'GET') target=null
      throw new TypeError('Synthetic lost response')
    }
    return response
  }}})
  clients.push(client)
  const {data:{session}}=await actor.client.auth.getSession()
  await ok(client.auth.setSession(session),'prepare response-loss session')
  return {client,dropNext:(path,method='POST')=>{target=path;targetMethod=method},restore:()=>{target=null}}
}
async function testResponseLoss() {
  const person=await account('personal'), business=await account('business')
  const personLoss=await responseLossClient(person),businessLoss=await responseLossClient(business)
  const lostBills=services(personLoss.client)('src/services/bills.service.ts')
  const billId=randomUUID(),billInput={user_id:person.user.id,name:'Lost-response bill',payee:'Synthetic payee',amount:15,currency:'USD',category:'other',due_date:'2026-01-01',recurrence:'once'}
  personLoss.dropNext('/rpc/create_money_record')
  await assert.rejects(lostBills.createBill(billInput,billId),/Could not confirm/)
  assert.equal((await lostBills.createBill(billInput,billId)).id,billId)
  await assert.rejects(lostBills.createBill({...billInput,amount:16},billId))
  assert.equal((await lostBills.getBills()).filter(b=>b.id===billId).length,1)
  const lostExpenses=services(personLoss.client)('src/services/expenses.service.ts')
  const expenseId=randomUUID(),expenseInput={user_id:person.user.id,expense_date:'2026-01-01',amount:15,currency:'USD',status:'DRAFT'}
  personLoss.dropNext('/rpc/create_money_record')
  await assert.rejects(lostExpenses.createExpense(expenseInput,expenseId),/Could not confirm/)
  assert.equal((await lostExpenses.createExpense(expenseInput,expenseId)).id,expenseId)
  await assert.rejects(lostExpenses.createExpense({...expenseInput,amount:16},expenseId))
  assert.equal((await lostExpenses.getExpenses()).filter(e=>e.id===expenseId).length,1)
  const unreadId=randomUUID()
  personLoss.dropNext('/expenses','GET')
  await assert.rejects(lostExpenses.createExpense({...expenseInput,amount:17},unreadId),/Could not confirm/)
  personLoss.restore()
  assert.equal((await lostExpenses.createExpense({...expenseInput,amount:17},unreadId)).id,unreadId)
  assert.equal((await lostExpenses.getExpenses()).filter(e=>e.id===unreadId).length,1)
  const api=services(businessLoss.client)('src/services/accounts-payable.service.ts')
  const vendor=await api.createVendor({user_id:business.user.id,organization_id:business.org.id,name:'Loss test supplier'})
  const input={vendor_id:vendor.id,bill_number:'LOSS-1',issue_date:'2026-01-01',due_date:'2026-02-01',tax_rate:0,currency:'USD'}
  const lines=[{description:'Synthetic work',quantity:1,rate:15,amount:15,order:0}]
  const vendorBillId=randomUUID()
  businessLoss.dropNext('/rpc/save_vendor_bill')
  await assert.rejects(api.createVendorBill(input,lines,vendorBillId),/Could not confirm/)
  assert.equal((await api.createVendorBill(input,lines,vendorBillId)).id,vendorBillId)
  await assert.rejects(api.createVendorBill({...input,notes:'Changed'},lines,vendorBillId))
  assert.equal((await api.getVendorBills()).length,1)
  console.log('PASS: bill/expense/vendor saves recover from deliberately lost responses: identical retries return the original record, altered requests fail, exactly one record remains')
}
async function main() {
  await testResponseLoss()
  const owner = await account('business'), outsider = await account('business'), freelancer = await account('freelancer'), personal = await account('personal')
  await denied(personal.client.from('users').update({ organization_id: owner.org.id, role: 'OWNER' }).eq('id',personal.user.id), 'cannot self-join another workspace')
  console.log('PASS: real Auth + RLS onboarding for business, freelancer and personal; foreign organization joining denied')
  const legacyOwner=await account('business')
  const legacyClient=await ok(legacyOwner.client.from('clients').insert({organization_id:legacyOwner.org.id,name:'Synthetic legacy client'}).select().single(),'create legacy client')
  const legacyInvoice=await ok(admin.from('invoices').insert({organization_id:legacyOwner.org.id,client_id:legacyClient.id,invoice_number:'LEGACY-QA',issue_date:'2025-01-01',due_date:'2025-02-01',subtotal:50,total:50,currency:'USD',status:'PAID',paid_at:'2025-01-20'}).select().single(),'seed synthetic legacy invoice')
  const legacyLoss=await responseLossClient(legacyOwner),legacyApi=services(legacyLoss.client)('src/services/invoices.service.ts')
  const legacyRequest=randomUUID(),legacyReview={action:'record_payment',amount:20,paid_on:'2025-01-15',method:'bank_transfer',reference:'Synthetic remittance',evidence:'Synthetic remittance reviewed for local testing'}
  assert.equal((await legacyApi.getLegacyPaidInvoices()).length,1)
  legacyLoss.dropNext('/rpc/review_legacy_payment')
  await assert.rejects(legacyApi.reviewLegacyPayment(legacyInvoice,legacyReview,legacyRequest),/Could not confirm/)
  await legacyApi.reviewLegacyPayment(legacyInvoice,legacyReview,legacyRequest)
  const reconciled=await legacyApi.getInvoice(legacyInvoice.id)
  assert.equal(reconciled.amount_paid,20);assert.equal(reconciled.balance_due,30)
  assert.equal(reconciled.legacy_reviews.length,1);assert.equal(reconciled.legacy_reviews[0].original_paid_at.slice(0,10),'2025-01-20')
  assert.equal((await legacyApi.getLegacyPaidInvoices()).length,0)
  await denied(outsider.client.from('legacy_payment_reviews').insert({id:randomUUID(),invoice_id:legacyInvoice.id}),'direct review insertion denied')
  assert.equal((await ok(outsider.client.from('legacy_payment_reviews').select('*'),'foreign reviews hidden')).length,0)
  console.log('PASS: legacy payment queue, evidence-backed partial receipt, lost-response recovery, preserved history, balance and cross-workspace denial')
  const membership = await ok(owner.client.from('workspace_memberships').select('*').single(), 'read own membership')
  assert.equal(membership.workspace_id,owner.org.id)
  await denied(owner.client.from('workspace_memberships').update({role:'OWNER'}).eq('user_id',outsider.user.id),'cannot forge membership')
  await Promise.all([{payment_terms:0},{default_currency:'EUR',accounting_basis:'accrual'}].map(p_patch=>ok(owner.client.rpc('set_own_preferences',{p_patch}),'save preferences')))
  const preferences=(await ok(owner.client.from('users').select('preferences').eq('id',owner.user.id).single(),'read preferences')).preferences
  assert.equal(preferences.payment_terms,0);assert.equal(preferences.default_currency,'EUR')
  await denied(owner.client.rpc('set_own_preferences',{p_patch:{role:'OWNER'}}),'unknown preference denied')
  const taxApi=services(freelancer.client)('src/services/tax.service.ts')
  await Promise.all([taxApi.seedQuarterlyEstimates(2026),taxApi.seedQuarterlyEstimates(2026)])
  assert.equal((await taxApi.getTaxFilings()).length,4)
  const billApi=services(personal.client)('src/services/bills.service.ts')
  const billInput={user_id:personal.user.id,name:'Synthetic local bill',payee:'Synthetic payee',amount:35,currency:'USD',category:'other',due_date:'2026-01-01',recurrence:'once'}
  const bill=await billApi.createBill(billInput)
  await assert.rejects(billApi.createBill(billInput))
  await billApi.markBillPaid(bill,'2026-01-02')
  await assert.rejects(billApi.cancelBill(bill))
  const billHistory=await services(personal.client)('src/services/review.service.ts').getRecordHistory('bills',bill.id)
  assert.equal(billHistory.length,2);assert.equal(billHistory[0].next_status,'paid')
  assert.equal(Number(billHistory[0].next_values.amount),35)
  const payableApi=services(owner.client)('src/services/accounts-payable.service.ts')
  const vendor=await payableApi.createVendor({user_id:owner.user.id,organization_id:owner.org.id,name:'Synthetic supplier',city:'Test city',payment_terms:0})
  assert.equal(vendor.city,'Test city');assert.equal(vendor.payment_terms,0)
  const vendorInput={user_id:owner.user.id,organization_id:owner.org.id,vendor_id:vendor.id,bill_number:'LOCAL-1',issue_date:'2026-01-01',due_date:'2026-02-01',tax_rate:10,currency:'USD'}
  const vendorBill=await payableApi.createVendorBill(vendorInput,[{description:'Synthetic service',quantity:2,rate:10,amount:20,order:0}])
  assert.equal(Number(vendorBill.total),22)
  await assert.rejects(payableApi.createVendorBill(vendorInput,[{description:'Synthetic service',quantity:2,rate:10,amount:20,order:0}]))
  const poLoss=await responseLossClient(owner),poApi=services(poLoss.client)('src/services/accounts-payable.service.ts')
  const poId=randomUUID(),poInput={vendor_id:vendor.id,po_number:'PO-LOCAL-1',date:'2026-01-01',tax_rate:10,currency:'USD'}
  const poLines=[{description:'Synthetic purchase',quantity:1,rate:15,amount:1,order:0}]
  poLoss.dropNext('/rpc/save_purchase_order')
  await assert.rejects(poApi.createPurchaseOrder(poInput,poLines,poId),/Could not confirm/)
  const po=await poApi.createPurchaseOrder(poInput,poLines,poId)
  assert.equal(Number(po.total),16.5)
  assert.equal((await poApi.getPurchaseOrders()).length,1)
  await poApi.purchaseOrderAction(po,'send')
  await assert.rejects(poApi.purchaseOrderAction(po,'receive'))
  const sentPO=(await poApi.getPurchaseOrders())[0]
  assert.equal(sentPO.status,'sent')
  await poApi.purchaseOrderAction(sentPO,'receive')
  await assert.rejects(poApi.purchaseOrderAction((await poApi.getPurchaseOrders())[0],'cancel'))
  assert.equal((await services(owner.client)('src/services/review.service.ts').getRecordHistory('purchase_orders',po.id)).length,3)
  assert.equal((await services(outsider.client)('src/services/accounts-payable.service.ts').getPurchaseOrders()).length,0)
  console.log('PASS: real API atomic purchase order totals, lost-response retry, versioned sent/received transitions, immutable terminal history and tenant isolation')
  await payableApi.markVendorBillPaid(vendorBill,'2026-01-10')
  await payableApi.archiveVendor(vendor.id)
  assert.equal((await payableApi.getVendorBills()).length,1)
  const contacts=await ok(owner.client.from('workspace_contacts').select('*').eq('id',vendor.id),'read archived contact')
  assert.equal(contacts.length,1);assert.ok(contacts[0].archived_at)
  assert.equal((await ok(outsider.client.from('workspace_contacts').select('*').eq('id',vendor.id),'foreign contacts invisible')).length,0)
  const reviewerEmail=`reviewer-${randomUUID()}@example.invalid`,reviewerPassword=randomBytes(24).toString('base64url')
  const {user:reviewerUser}=await ok(admin.auth.admin.createUser({email:reviewerEmail,password:reviewerPassword,email_confirm:true}),'local reviewer auth fixture')
  await ok(admin.from('users').insert({id:reviewerUser.id,email:reviewerEmail,name:'Synthetic reviewer',account_type:'business',role:'ADMIN',organization_id:owner.org.id}),'local reviewer profile')
  const reviewer=createClient(s.API_URL,s.ANON_KEY,options);clients.push(reviewer)
  await ok(reviewer.auth.signInWithPassword({email:reviewerEmail,password:reviewerPassword}),'reviewer sign in')
  const expenseApi=services(owner.client)('src/services/expenses.service.ts')
  const expenseId=randomUUID(),expenseInput={user_id:owner.user.id,amount:12,currency:'USD',expense_date:'2026-01-01',status:'DRAFT'}
  let reviewedExpense=await expenseApi.createExpense(expenseInput,expenseId)
  assert.equal((await expenseApi.createExpense(expenseInput,expenseId)).id,expenseId)
  const reviewApi=services(owner.client)('src/services/review.service.ts')
  await reviewApi.reviewWorkRecord('expenses',expenseId,'submit',reviewedExpense.updated_at)
  reviewedExpense=await expenseApi.getExpense(expenseId)
  await assert.rejects(reviewApi.reviewWorkRecord('expenses',expenseId,'approve',reviewedExpense.updated_at))
  await services(reviewer)('src/services/review.service.ts').reviewWorkRecord('expenses',expenseId,'approve',reviewedExpense.updated_at)
  assert.equal((await expenseApi.getExpense(expenseId)).status,'APPROVED')
  await assert.rejects(expenseApi.archiveExpense(expenseId,reviewedExpense.updated_at))
  assert.equal((await reviewApi.getRecordHistory('expenses',expenseId)).length,3)
  console.log('PASS: real API memberships, concurrent settings, bill duplicates/history, atomic vendor bills, archived contacts, expense retries and independent review')
  const pageA=await fetch(appOrigin+'/login',{headers:{'x-nonce':'forged'}}),pageB=await fetch(appOrigin+'/login')
  const policyA=pageA.headers.get('content-security-policy'),policyB=pageB.headers.get('content-security-policy')
  const nonceA=policyA?.match(/'nonce-([^']+)'/)?.[1],nonceB=policyB?.match(/'nonce-([^']+)'/)?.[1]
  assert.ok(nonceA&&nonceB&&nonceA!==nonceB&&nonceA!=='forged')
  assert.ok((await pageA.text()).includes(`nonce="${nonceA}"`))
  assert.ok(pageA.headers.get('cache-control').includes('no-store'))
  console.log('PASS: actual page responses rotate CSP nonces, override forged headers and avoid shared caching')
  const load = services(owner.client)
  const expenseService = load('src/services/expenses.service.ts')
  const file = new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN9kAAAAASUVORK5CYII=', 'base64')], 'synthetic.png', { type: 'image/png' })
  const receiptPath = await expenseService.uploadReceipt(file)
  const signedUrl = await expenseService.getReceiptUrl({ receipt_path: receiptPath })
  assert.equal((await fetch(signedUrl)).status, 200)
  const signedAt = Date.now()
  await assert.rejects(services(outsider.client)('src/services/expenses.service.ts').getReceiptUrl({ receipt_path: receiptPath }))
  await denied(outsider.client.storage.from('receipts').upload(`${owner.user.id}/${randomUUID()}.png`, file), 'cannot upload to foreign receipt prefix')
  await assert.rejects(expenseService.uploadReceipt(new File(['bad'], 'bad.html', { type: 'text/html' })))
  await assert.rejects(expenseService.uploadReceipt(new File([new Uint8Array(10*1024*1024+1)], 'large.png', { type:'image/png' })))
  await assert.rejects(expenseService.getReceiptUrl({receipt_url:'https://example.invalid/storage/v1/object/sign/receipts/fake'}))
  console.log('PASS: receipt upload/open, cross-workspace signing/upload denial, invalid types/sizes/legacy origins rejected')
  const customer = await ok(owner.client.from('clients').insert({ organization_id: owner.org.id, name: 'Synthetic client' }).select().single(), 'create client')
  const rows = Array.from({length:1005},(_,n)=>({id:randomUUID(),organization_id:owner.org.id,client_id:customer.id,invoice_number:`BULK-${n}`,issue_date:'2026-01-01',due_date:'2026-02-01',subtotal:1,total:1,status:'SENT'}))
  await ok(admin.from('invoices').insert(rows), 'seed large dataset locally')
  await ok(admin.from('invoice_payments').insert(rows.map(row=>({id:randomUUID(),invoice_id:row.id,amount:0.5,paid_on:'2026-01-02',method:'other',recorded_by:owner.user.id}))), 'seed partial payments locally')
  const invoices = await load('src/services/invoices.service.ts').getInvoices()
  assert.equal(invoices.length,1005); assert.equal(new Set(invoices.map(row=>row.id)).size,1005)
  assert.equal(invoices.reduce((total,row)=>total+row.balance_due,0),502.5)
  const exports = load('src/services/exports.service.ts')
  const exported = await exports.getExportRows('invoices'), exportedPayments = await exports.getExportRows('invoice_payments')
  assert.equal(exported.length,1005); assert.equal(exportedPayments.length,1005)
  assert.ok(exported.every(row=>!Object.hasOwn(row,'issued_snapshot')))
  await ok(owner.client.from('expenses').insert({user_id:owner.user.id,expense_date:'2026-01-01',amount:1,receipt_path:receiptPath}), 'save receipt reference')
  const exportedExpenses = await exports.getExportRows('expenses')
  assert.equal(exportedExpenses.length,2); assert.ok(exportedExpenses.every(row=>!Object.hasOwn(row,'receipt_path')&&!Object.hasOwn(row,'receipt_url')))
  assert.equal((await services(outsider.client)('src/services/exports.service.ts').getExportRows('invoices')).length,0)
  await assert.rejects(exports.getExportRows('users'))
  console.log('PASS: actual invoice/payment/export services read all 1,005 rows beyond the API cap; balances, export redaction and isolation verified')
  const invoiceService = load('src/services/invoices.service.ts')
  const second = createClient(s.API_URL,s.ANON_KEY,options);clients.push(second)
  await ok(second.auth.signInWithPassword({email:owner.email,password:owner.password}), 'second independent session')
  const otherSession = services(second)('src/services/invoices.service.ts')
  const id = randomUUID(), input = {client_id:customer.id,issue_date:'2026-01-01',due_date:'2026-02-01',tax_rate:0,currency:'USD'}, lines=[{description:'Retry test',quantity:1,rate:100}]
  await invoiceService.saveInvoiceDraft(id,input,lines)
  const firstView = await invoiceService.getInvoice(id), secondView = await otherSession.getInvoice(id)
  await invoiceService.saveInvoiceDraft(id,{...input,notes:'First writer'},lines,firstView.updated_at)
  await assert.rejects(otherSession.saveInvoiceDraft(id,{...input,notes:'Stale writer'},lines,secondView.updated_at), error=>error.code==='PT409')
  await invoiceService.invoiceAction(await invoiceService.getInvoice(id),'issue')
  // Discard a successful result, as if its response was lost, then retry the same request.
  const payment={id:randomUUID(),amount:40,paid_on:'2026-01-15',method:'other',reference:'Synthetic retry'}
  await invoiceService.recordInvoicePayment(id,payment)
  await otherSession.recordInvoicePayment(id,payment)
  assert.equal((await invoiceService.getInvoice(id)).payments.length,1)
  const race = await Promise.allSettled([invoiceService,otherSession].map(api=>api.recordInvoicePayment(id,{...payment,id:randomUUID(),amount:60})))
  assert.equal(race.filter(result=>result.status==='fulfilled').length,1)
  assert.equal((await invoiceService.getInvoice(id)).balance_due,0)
  console.log('PASS: two real sessions reject stale edits; response-loss retry is idempotent; concurrent final payments cannot overpay')
  const correctionId=randomUUID()
  const correctionLoss=await responseLossClient(owner)
  correctionLoss.dropNext('/rpc/reverse_invoice_payment')
  await assert.rejects(services(correctionLoss.client)('src/services/invoices.service.ts').reverseInvoicePayment(correctionId,payment.id,'Incorrect receipt recorded during synthetic test'))
  await otherSession.reverseInvoicePayment(correctionId,payment.id,'Incorrect receipt recorded during synthetic test')
  const corrected=await invoiceService.getInvoice(id)
  assert.equal(corrected.balance_due,40); assert.equal(corrected.amount_paid,60)
  assert.ok(corrected.payments.find(row=>row.id===payment.id).reversal)
  await assert.rejects(services(outsider.client)('src/services/invoices.service.ts').reverseInvoicePayment(randomUUID(),payment.id,'Foreign correction attempt'))
  await invoiceService.recordInvoicePayment(id,{...payment,id:randomUUID(),reference:'Correct replacement'})
  assert.equal((await invoiceService.getInvoice(id)).balance_due,0)
  assert.equal((await exports.getExportRows('invoice_payment_reversals')).length,1)
  const freelancerLoad=services(freelancer.client), freelancerApi=freelancerLoad('src/services/invoices.service.ts')
  const timeClient=await ok(freelancer.client.from('clients').insert({user_id:freelancer.user.id,name:'Synthetic time client'}).select().single(),'create time client')
  const timeProject=await ok(freelancer.client.from('projects').insert({user_id:freelancer.user.id,client_id:timeClient.id,name:'Synthetic time project',billing_model:'HOURLY'}).select().single(),'create time project')
  const timeEntry=await freelancerLoad('src/services/time-entries.service.ts').createTimeEntry({user_id:freelancer.user.id,project_id:timeProject.id,start_at:'2026-01-01T09:00:00Z',end_at:'2026-01-01T10:01:00Z',duration_minutes:61,billable_rate:100,status:'DRAFT',notes:'Synthetic tracked work'})
  const timeInput={...input,client_id:timeClient.id,project_id:timeProject.id}, timeInvoiceId=randomUUID()
  await freelancerApi.createInvoiceFromTime(timeInvoiceId,[timeEntry.id],timeInput)
  await freelancerApi.createInvoiceFromTime(timeInvoiceId,[timeEntry.id],timeInput)
  await assert.rejects(freelancerApi.createInvoiceFromTime(randomUUID(),[timeEntry.id],timeInput))
  const timeInvoice=await freelancerApi.getInvoice(timeInvoiceId)
  assert.equal(timeInvoice.total,101.67); assert.equal(timeInvoice.time_links.length,1)
  const tracked=await freelancerLoad('src/services/time-entries.service.ts').getTimeEntries()
  assert.equal(tracked[0].billing_links[0].invoice_id,timeInvoiceId)
  await freelancerApi.invoiceAction(timeInvoice,'issue')
  await freelancerApi.invoiceAction(await freelancerApi.getInvoice(timeInvoiceId),'cancel')
  await freelancerApi.createInvoiceFromTime(randomUUID(),[timeEntry.id],timeInput)
  console.log('PASS: real API payment correction/retry/replacement/export and time reservation/retry/duplicate denial/cancellation/rebilling')
  const ownerCookie = await cookieHeader(owner), outsiderCookie = await cookieHeader(outsider)
  const pdfUrl = `${appOrigin}/api/invoices/${id}/pdf`
  assert.equal((await fetch(pdfUrl)).status,401)
  assert.equal((await fetch(pdfUrl,{headers:{cookie:outsiderCookie}})).status,404)
  assert.equal((await fetch(`${appOrigin}/api/invoices/not-a-uuid/pdf`,{headers:{cookie:ownerCookie}})).status,400)
  const pdfResponse = await fetch(pdfUrl,{headers:{cookie:ownerCookie}})
  assert.equal(pdfResponse.status,200)
  assert.equal(pdfResponse.headers.get('content-type'),'application/pdf')
  assert.match(pdfResponse.headers.get('cache-control'),/no-store/)
  assert.match(pdfResponse.headers.get('content-disposition'),/^attachment;/)
  assert.equal((await pdfResponse.text()).slice(0,5),'%PDF-')
  const { data: { session: ownerSession } } = await owner.client.auth.getSession()
  const aiHeaders = {origin:appOrigin,authorization:`Bearer ${ownerSession.access_token}`,'content-type':'application/json'}
  const aiBody = JSON.stringify({task:'invoice_line',payload:'Synthetic work at 10'})
  assert.equal((await fetch(`${appOrigin}/api/ai`,{method:'POST',headers:aiHeaders,body:aiBody})).status,503)
  assert.equal((await fetch(`${appOrigin}/api/ai`,{method:'POST',headers:{...aiHeaders,origin:'https://example.invalid'},body:aiBody})).status,403)
  console.log('PASS: production-mode same-origin AI request reaches disabled-provider fallback; cross-origin request denied')
  console.log('PASS: authenticated PDF route renders a real PDF; anonymous, foreign-workspace and malformed requests denied; private/no-store headers set')
  await ok(admin.from('users').update({is_active:false}).eq('id',owner.user.id),'disable synthetic user')
  assert.equal((await invoiceService.getInvoices()).length,0)
  assert.equal((await fetch(pdfUrl,{headers:{cookie:ownerCookie}})).status,404)
  await assert.rejects(expenseService.getReceiptUrl({receipt_path:receiptPath}))
  await assert.rejects(invoiceService.saveInvoiceDraft(randomUUID(),input,lines))
  await ok(admin.from('users').update({is_active:true,role:'MEMBER'}).eq('id',owner.user.id),'demote synthetic user')
  assert.equal((await invoiceService.getInvoices()).length,0)
  await assert.rejects(invoiceService.recordInvoicePayment(id,{...payment,id:randomUUID(),amount:1}))
  await ok(admin.from('users').update({role:'OWNER'}).eq('id',owner.user.id),'restore synthetic role')
  const jwtPart = value => Buffer.from(JSON.stringify(value)).toString('base64url')
  const expired = [jwtPart({alg:'HS256',typ:'JWT'}),jwtPart({sub:owner.user.id,role:'authenticated',aud:'authenticated',exp:1})].join('.')
  const token = `${expired}.${createHmac('sha256',s.JWT_SECRET).update(expired).digest('base64url')}`
  const response = await fetch(`${s.API_URL}/rest/v1/invoices?select=id`,{headers:{apikey:s.ANON_KEY,authorization:`Bearer ${token}`}})
  assert.equal(response.status,401)
  console.log('PASS: disabled users, role changes and expired sessions are denied through real API requests')
  // The application requests 60-second URLs; wait only the remaining lifetime.
  await new Promise(resolve=>setTimeout(resolve,Math.max(0, signedAt+65000-Date.now())))
  assert.notEqual((await fetch(signedUrl,{cache:'no-store'})).status,200)
  const fresh = await expenseService.getReceiptUrl({receipt_path:receiptPath})
  assert.equal((await fetch(fresh)).status,200)
  console.log('PASS: actual 60-second receipt link expires; a fresh authorized link opens')
}
main().catch(error=>{console.error('FAIL:',error.name,error.message);process.exitCode=1}).finally(()=>{for(const client of clients)client.auth.stopAutoRefresh()})
