const assert = require('node:assert/strict')
const { test } = require('node:test')
const app = require('./load-app.cjs')()
const report = app('src/lib/reporting.ts')
const invoice = (extra = {}) => ({ id:'i', invoice_number:'QA', status:'SENT', currency:'USD', issue_date:'2025-12-31', total:100, payments:[], ...extra })
test('cash reports actual unreversed receipts in payment year, never legacy paid status', () => {
  const rows = [invoice({payments:[{id:'p1',paid_on:'2025-12-31',amount:20},{id:'p2',paid_on:'2026-01-01',amount:30},{id:'p3',paid_on:'2026-01-02',amount:50,reversal:{id:'r'}}]}),invoice({id:'legacy',status:'PAID'}),invoice({id:'eur',currency:'EUR',payments:[{paid_on:'2026-01-01',amount:500}]})]
  assert.equal(report.sumMoney(report.incomeRecords(rows,2026,'USD','cash')),30)
  assert.equal(report.sumMoney(report.incomeRecords(rows,2025,'USD','cash')),20)
  assert.equal(report.incomeRecords(rows,2026,'USD','accrual').length,0)
  assert.equal(report.sumMoney(report.incomeRecords(rows,2025,'USD','accrual')),200)
})
test('drafts/cancellations never count and currencies are separate',()=>{
  const rows=['DRAFT','CANCELLED','SENT'].map(status=>invoice({status}))
  assert.equal(report.incomeRecords(rows,2025,'USD','accrual').length,1)
  assert.equal(report.incomeRecords(rows,2025,'EUR','accrual').length,0)
  const expenses=[{expense_date:'2026-01-01',currency:'USD',amount:.1,status:'DRAFT'},{expense_date:'2026-02-01',currency:'USD',amount:.2,status:'APPROVED'},{expense_date:'2025-12-31',currency:'USD',amount:10},{expense_date:'2026-01-01',currency:'EUR',amount:10},{expense_date:'2026-01-01',currency:'USD',amount:10,status:'REJECTED'}]
  assert.equal(report.sumMoney(report.expenseRecords(expenses,2026,'USD')),.3)
})
test('reviewed single-filer thresholds and Social Security cap are year specific',()=>{
  assert.equal(report.estimateFederalTax(16100,2026),0)
  assert.equal(report.estimateFederalTax(28500,2026),1240)
  assert.equal(report.estimateFederalTax(28600,2026),1252)
  assert.equal(report.estimateFederalTax(15750+11925,2025),1192.5)
  assert.equal(report.estimateSETax(399,2026),0)
  assert.equal(report.estimateSETax(200000,2026),184500*.124+200000*.029)
  assert.equal(report.estimateSETax(200000,2025),176100*.124+200000*.029)
  assert.throws(()=>report.estimateFederalTax(1,2027))
  assert.throws(()=>report.estimateSETax(NaN,2026))
})
test('estimated tax periods and shifted deadlines use calendar rules',()=>{
  assert.equal(report.taxQuarters(2025)[1].dueDate,'2025-06-16')
  assert.equal(report.taxQuarters(2026)[1].dueDate,'2026-06-15')
  assert.equal(report.taxQuarters(2026)[1].end,'2026-05-31')
  assert.equal(report.taxQuarters(2026)[3].dueDate,'2027-01-15')
  assert.throws(()=>report.taxQuarters(2027))
})
test('production CSP limits scripts to nonces and backend connections to configured origin',()=>{
  const {contentSecurityPolicy:csp}=app('src/lib/content-security-policy.ts')
  const policy=csp('testnonce','https://backend.example.invalid/some/path',false)
  assert.ok(policy.includes("script-src 'self' 'nonce-testnonce' 'strict-dynamic';"))
  assert.ok(!policy.includes('unsafe-eval'))
  assert.ok(policy.includes("connect-src 'self' https://backend.example.invalid wss://backend.example.invalid;"))
  assert.throws(()=>csp("bad'; script-src *",undefined,false))
  assert.throws(()=>csp('test','http://external.example.invalid',false))
  assert.ok(csp('test','http://127.0.0.1:54321',true).includes("'unsafe-eval'"))
})
