// Self-contained MCP App: no external scripts, network access, HTML interpolation,
// tokens, record text in markup, or automatic model messages.
export const panelHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
body{font:15px system-ui,sans-serif;color:#172033;background:#fafbfc;margin:0;padding:24px}h1{font-size:24px}button,input,select{font:inherit;padding:9px;border:1px solid #cbd5e1;border-radius:8px}button{cursor:pointer;background:#eef2ff}form,nav{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}label{display:grid;gap:4px}li{padding:14px 0;border-bottom:1px solid #ddd}p{line-height:1.5}.muted{color:#536174}.summary{background:#e8f3ef;padding:16px;border-radius:12px}a{color:#12584b}button[aria-pressed=true]{background:#164e43;color:white}</style></head><body>
<h1>Financial review</h1><p class="muted">Read-only findings with supporting records.</p>
<form id="form"><label>From<input id="start" type="date" required></label><label>Through<input id="end" type="date" required></label><label>Currency<select id="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>AUD</option></select></label><button>Refresh review</button></form>
<p id="status" role="status">Open a financial review to begin.</p><nav aria-label="Review views"><button data-view="findings">Findings</button><button data-view="unpaid">Unpaid invoices</button><button data-view="obligations">Upcoming bills</button></nav><p id="summary" class="summary"></p><ul id="records"></ul><div id="notes" class="muted"></div>
<script>
const pending=new Map();let seq=0,review,view='findings';const $=id=>document.getElementById(id);
function rpc(method,params){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Timeout'))},15000);pending.set(id,{resolve,reject,timer});parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function render(data){if(!data||!data.period||!Array.isArray(data.findings)||!Array.isArray(data.unpaid)||!Array.isArray(data.obligations))throw new Error('Invalid review');review=data;for(const key of ['start','end','currency'])$(key).value=data.period[key];$('status').textContent=(data.synthetic?'Synthetic sample · ':'')+'As of '+data.asOf;$('summary').textContent='Outstanding '+data.totals.unpaid.toFixed(2)+' · Obligations '+data.totals.obligations.toFixed(2)+' · Period expenses '+data.totals.expenses.toFixed(2)+' '+data.period.currency;$('records').replaceChildren();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));for(const row of data[view]){const li=document.createElement('li'),strong=document.createElement('strong'),p=document.createElement('p'),a=document.createElement('button');strong.textContent=row.title||row.source.label;p.textContent=row.detail||(row.amount.toFixed(2)+' '+data.period.currency+' · Due '+row.due);a.textContent='Supporting record: '+row.source.label;a.onclick=async()=>{a.disabled=true;try{const result=await rpc('tools/call',{name:'get_financial_record',arguments:{kind:row.source.kind,id:row.source.id}});if(result.isError)throw new Error('Unavailable');const r=result.structuredContent,details=document.createElement('p');details.textContent=r.label+' · Recorded amount: '+r.amount.toFixed(2)+' '+r.currency+' · '+r.date+' · Recorded status: '+r.status;li.append(details)}catch{a.textContent='Record unavailable. Try again.';a.disabled=false}};li.append(strong,p,a);$('records').append(li)}if(!data[view].length){const li=document.createElement('li');li.textContent='No matching records.';$('records').append(li)}$('notes').replaceChildren();for(const note of data.notes){const p=document.createElement('p');p.textContent=note;$('notes').append(p)}}
window.addEventListener('message',event=>{if(event.source!==parent||!event.data||event.data.jsonrpc!=='2.0')return;const m=event.data;if(pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(new Error('Request failed')):p.resolve(m.result)}if(m.method==='ui/notifications/tool-result'){try{render(m.params.structuredContent)}catch{$('status').textContent='Could not display this review.'}}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;if(review)render(review)});
$('form').onsubmit=async e=>{e.preventDefault();$('status').textContent='Reviewing…';try{const result=await rpc('tools/call',{name:'review_period',arguments:{start:$('start').value,end:$('end').value,currency:$('currency').value}});if(result.isError)throw new Error('Failed');render(result.structuredContent)}catch{$('status').textContent='Could not refresh. Showing the previous result; try again.'}};
rpc('ui/initialize',{appInfo:{name:'Amountly Review',version:'0.1.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',params:{}},'*')).catch(()=>{$('status').textContent='Open this panel through the Amountly plugin.'});
</script></body></html>`
