import { PolicyPage } from '@/components/policy-page'
export default function Page() {
  return <PolicyPage title="Privacy policy"><p>Effective October 3, 2026. Amountly is operated by Mac Digital. Contact: <a href="mailto:info@macdigital.ai" className="underline">info@macdigital.ai</a>.</p>
    <h2 className="text-xl font-semibold">Information and purpose</h2><p>Amountly stores your account information and the financial records and receipt files you choose to add. We use them to authenticate you, provide bookkeeping features, enforce account and organization permissions, and protect the service. Do not enter payment-card credentials, government identification numbers, medical records or passwords into financial record descriptions.</p>
    <h2 className="text-xl font-semibold">Connecting to ChatGPT</h2><p>Connecting is optional and requires your consent. When you use the Amountly tools, we share the requested financial amounts, currencies, dates, statuses, record identifiers, receipt-presence flags, calculated summaries and supporting links with OpenAI. If you approve the email permission, OpenAI can also retrieve your verified account email to identify the connection. Raw record descriptions, customer identifiers, receipt files, receipt access URLs and Amountly passwords are excluded from these tool responses.</p><p>The integration reads records you can already access. It cannot change records, send messages, move money or file taxes. OpenAI processes the data it receives under its applicable terms and privacy settings. Disconnecting prevents future access; it does not remove information already present in your ChatGPT conversations. Manage that information in ChatGPT.</p>
    <h2 className="text-xl font-semibold">Service providers and security</h2><p>Render hosts the application and database. Proton provides account email delivery. OpenAI processes ChatGPT tool results and data submitted through optional AI features when you use those features. We do not sell your financial records or use them for advertising. Access uses secure sessions, scoped OAuth permissions and database ownership checks. Runtime credentials are stored in server configuration.</p>
    <h2 className="text-xl font-semibold">Retention and control</h2><p>Account and financial records remain until removed through supported workflows or an approved deletion request. Access tokens expire after ten minutes; rotating refresh tokens expire within seven days and can be revoked sooner. We store token hashes rather than bearer tokens. Minimal integration audit events contain the account ID, tool name, outcome and time, and are pruned hourly after 30 days. These events contain no prompts, financial values, receipt content or tool results.</p><p>Operational backups and migration recovery copies may temporarily retain data after deletion from the active system. Support will identify applicable backup retention or legal recordkeeping requirements when handling your request. We do not promise immediate erasure from backups.</p><p>You can review and export records in Amountly, <a href="/chatgpt/connections" className="underline">revoke ChatGPT access</a>, or <a href="/support" className="underline">request access, correction or deletion</a>. We verify account ownership before acting on requests. Contact support with any privacy concern.</p>
  </PolicyPage>
}
